version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.21
    working_directory: /go/src/github.com/tanqiangyes/govalidator
    steps:
      - checkout
      - run: diff -u /dev/null <(gofmt -d .)
      - run: go get -v -t -d ./...
      - run: go test -v ./...
